### ISSUE TITLE
Another ghost record example

### ISSUE THREAD

**Issue by jhammock** [EOL/ContentImport#10]
A user has reported some dubious interpretations of our wikipedia-mined data records, https://opendata.eol.org/dataset/wikip/resource/202fc4df-a6b3-4c12-8beb-6be8091bbbe0
https://content.eol.org/resources/512

The records in question appear in:
https://eol.org/pages/591632/data?predicate_id=1002

("city", "house")

They're not in the resource file. I think we actually have two processes in place now that would prevent them from being included- both strings appear in the References section of the article, and both are probably no longer on our list of terms to include. Can we add this resource to the queue for ghost-record-delete testing? It and GloBI are probably our largest source of records-that-should-have-been-deleted.

**Comment by eliagbayani** [comment]
Noted @jhammock .
Correct, both entries are no longer in the [resource file](https://opendata.eol.org/dataset/wikip/resource/202fc4df-a6b3-4c12-8beb-6be8091bbbe0). Together with Wikipedia and GloBI, TRY is another one.
- Wikipedia (inferred records) 
-- This may just need to be reharvested-then-republished since it is already due. Harvesting may still have used an old DwCA file.
- [TRY database](https://github.com/EOL/ContentImport/issues/7#issuecomment-2089399263)
- GloBI

Will remind Jeremy of our ghost-record-delete pending resources once he finishes the publish-index issue.
Will try to republish in small-big size order (as listed above).
Thanks.

**Comment by eliagbayani** [comment]
@jhammock @JRice 
Good news.
I just reharvested and republished Wikipedia (inferred records) successfully.
Ghost MoF records 'city', 'house' now removed for:
https://eol.org/pages/591632/data?predicate_id=1002
Thanks.

**Comment by jhammock** [comment]
Excellent!
